name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t streamlit-app .

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker tag streamlit-app:latest yojs/streamlit-app:latest 
          docker push yojs/streamlit-app:latest 

      - name: Deploy to Server
        run: |
          mkdir -p ~/.ssh || echo "Directory already exists"
          echo "Writing SSH private key..."
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "Key written. Setting permissions..."
          chmod 600 ~/.ssh/id_rsa
          echo "Checking contents of ~/.ssh:"
          ls -la ~/.ssh
          ssh-keyscan -H 49.36.35.138 >> ~/.ssh/known_hosts
          echo "Attempting to connect to server..."
          ssh -v ubuntu@49.36.35.138 "docker pull yojs/streamlit-app:latest && docker run -d -p 8501:8501 yojs/streamlit-app:latest"
      
      
      
      
      
